try:
# code inside the try block which can cause an exception
# taking the input ‘name’ from the user
    while True :
        print("Hello")
except KeyboardInterrupt:
    print('World')
